@MedicalSuiteNova_HostAddress = https://localhost:7209
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInVuaXF1ZV9uYW1lIjoiYWRtaW4iLCJqdGkiOiI5NDYwMDljYy1kOGJjLTQwYzEtYjM2My1mYzZhZDljMDk3NzQiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3NzYxMzM2ODcsImV4cCI6MTc3NjczODQ4NywiaWF0IjoxNzc2MTMzNjg3LCJpc3MiOiIxMjMiLCJhdWQiOiIxMjMifQ.pevaCxuzd2sSRHBnq0aW_Hk1qiocXWOrCcffw3jTXO0

### GET AUTH
# @name login
GET {{MedicalSuiteNova_HostAddress}}/api/auth
Accept: application/json
###
@Token = {{login.response.body.token}}

### GET ALL
GET {{MedicalSuiteNova_HostAddress}}/api/invoice?pageNumber=1&pageSize=5
Authorization: Bearer {{Token}}
Accept: application/json
### Invoice
POST {{MedicalSuiteNova_HostAddress}}/api/invoice
Accept: application/json
Content-Type: application/json

{
  "CustomerId": 1,
  "CurrencyId": 1,
  "CreatedBy": "ingenierfonseca",
  "Items": [
    {
      "Description": "Extracción Molar",
      "Quantity": 2,
      "UnitPrice": 600,
      "Discount": 0,
      "TaxAmount": "15"
    },
    {
      "Description": "Calsa Molar",
      "Quantity": 4,
      "UnitPrice": 500,
      "Discount": 0,
      "TaxAmount": "15"
    },
    {
      "Description": "Limpieza General",
      "Quantity": 1,
      "UnitPrice": 700,
      "Discount": 0,
      "TaxAmount": "15"
    }
  ]
}
### Invoice
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/1
Accept: application/json

### Invoice Dashboard
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/dashboard?pageNumber=1&pageSize=5&search=
Accept: application/json

### Invoice Dashboard
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/dashboard-customers?pageNumber=1&pageSize=5&search=
Accept: application/json

### Invoice Customer
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/customer/2
Authorization: Bearer {{Token}}
Accept: application/json

### Invoice Customer Pyments
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/customer/2/payments
Accept: application/json


### PUT Invoice
PUT {{MedicalSuiteNova_HostAddress}}/api/invoice/1
Authorization: Bearer {{Token}}
Accept: application/json
Content-Type: application/json

{
  "customerId": 2,
  "number": "FAC-2026-000002",
  "issueDate": "2026-04-09T00:00:00",
  "dueDate": "2026-04-09T03:12:26.203",
  "subTotal": 400.00,
  "taxTotal": 0.00,
  "discountTotal": 0.00,
  "total": 400.00,
  "currencyId": 2,
  "statusId": 5,
  "paymentTermId": 1,
  "createdAt": "2026-04-09T03:12:26.203",
  "createdBy": ""
}
