@MedicalSuiteNova_HostAddress = https://localhost:7209
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZG1pbiIsInVuaXF1ZV9uYW1lIjoiYWRtaW4iLCJqdGkiOiI3ZTMxZDIyMS1mNGJlLTQ1NjAtOWYwYi04MzFmZjE5M2E0ZTkiLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3NzY3Mzg4NjYsImV4cCI6MTc3NzM0MzY2NiwiaWF0IjoxNzc2NzM4ODY2LCJpc3MiOiIxMjMiLCJhdWQiOiIxMjMifQ.I7B3E6VZbqgBp0Mf09qkigGpJ8DWSo14IqdXLpwzXag

### GET AUTH
# @name login
GET {{MedicalSuiteNova_HostAddress}}/api/auth
Accept: application/json
###
@Token = {{login.response.body.token}}

### GET ALL
GET {{MedicalSuiteNova_HostAddress}}/api/invoice?pageNumber=1&pageSize=5
Authorization: Bearer {{Token}}
Accept: application/json
### Invoice
POST {{MedicalSuiteNova_HostAddress}}/api/invoice
Authorization: Bearer {{Token}}
Accept: application/json
Content-Type: application/json

{
  "CustomerId": 2,
  "CurrencyId": 1,
  "PaymentTermId": 2,
  "IssueDate": "2026-04-01T00:00:00",
  "CreatedBy": "ingenierfonseca",
  "Items": [
    {
      "Description": "Limpieza dental",
      "Quantity": 2,
      "Discount": 0,
      "TaxAmount": "15"
    },
    {
      "Description": "Extracción dent",
      "Quantity": 4,
      "Discount": 0,
      "TaxAmount": "15"
    }
  ]
}
### Invoice
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/1
Accept: application/json

### Invoice Dashboard
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/dashboard?pageNumber=1&pageSize=5&search=
Accept: application/json

### Invoice Dashboard
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/dashboard-customers?pageNumber=1&pageSize=5&search=
Accept: application/json

### Invoice Customer
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/customer/2
Authorization: Bearer {{Token}}
Accept: application/json

### Invoice Customer Pyments
GET {{MedicalSuiteNova_HostAddress}}/api/invoice/customer/2/payments
Accept: application/json


### PUT Invoice
PUT {{MedicalSuiteNova_HostAddress}}/api/invoice/1
Authorization: Bearer {{Token}}
Accept: application/json
Content-Type: application/json

{
  "customerId": 2,
  "number": "FAC-2026-000002",
  "issueDate": "2026-04-09T00:00:00",
  "dueDate": "2026-04-09T03:12:26.203",
  "subTotal": 400.00,
  "taxTotal": 0.00,
  "discountTotal": 0.00,
  "total": 400.00,
  "currencyId": 2,
  "statusId": 5,
  "paymentTermId": 1,
  "createdAt": "2026-04-09T03:12:26.203",
  "createdBy": ""
}
